---
- name: Terraform - Create download directory.
  file:
    state: directory
    mode: u=rwx,go=rx
    dest: "{{ terraform_download_dir }}"

- name: Terraform - Download.
  get_url:
    url: "{{ terraform_url_download }}"
    dest: "{{ terraform_download_dir }}/{{ terraform_filename }}"
    mode: u=rw,go=r

- name: Terraform - Create installation directory.
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: u=rwx,go=rx
    dest: "{{ terraform_install_dir }}"

- name: Terraform - Unzip.
  become: yes
  unarchive:
    src: "{{ terraform_download_dir }}/{{ terraform_filename }}"
    remote_src: yes
    dest: "{{ terraform_download_dir }}"
    
- name: Terraform - Install.
  become: yes
  copy:
    remote_src: yes
    src: "{{ terraform_download_dir }}/terraform"
    dest: "{{ terraform_install_dir }}"
    owner: root
    group: root
    mode: u=rwx,go=rx
